# Generated by Django 5.1.2 on 2024-10-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "itemID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("itemName", models.CharField(max_length=100)),
                ("itemPoster", models.CharField(max_length=250)),
                ("itemRating", models.FloatField()),
                ("itemType", models.CharField(max_length=10)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
