# Generated by Django 5.1.2 on 2024-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_watchlist_itemname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="itemType",
            field=models.CharField(default="tv", max_length=10),
            preserve_default=False,
        ),
    ]
