# Generated by Django 5.1.2 on 2024-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_watchlist_itemtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="itemPoster",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="itemRating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="itemTitle",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="itemType",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
